# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory: 
                users:
                    richpolis:
                        password: D3m3s1s1
                        roles: 'ROLE_ADMIN'
                    admin:
                        password: 1234
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/backend
            provider: in_memory
            form_login:
                login_path: backend_login
                check_path: backend_login_check
            logout:
                path: backend_logout
                target: backend_login
            security: true
            anonymous: true
    
    access_control:
    - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/, roles: ROLE_ADMIN }
    