<?php

namespace YDI\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelefonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientoRepository extends EntityRepository
{
    public function getDistinctEstados() {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT DISTINCT e.estado as estado '
                    . 'FROM YDIBackendBundle:Establecimiento e '
                    . 'GROUP BY e.estado');
        return $consulta->getResult();
    }
}