<?php

namespace YDI\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelefonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefonoRepository extends EntityRepository
{
    public function getTelefonosEnviarNotificacion($limit) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT t '
                . 'FROM YDIBackendBundle:Telefono t '
                . 'WHERE t.enviarNotificacion = :enviar AND '
                . 't.inactivo = :inactivo AND '
				. 't.registroBorrado = :registroborrado');
        $consulta->setParameters(array(
            'enviar' => true,
            'inactivo' => false,
			'registroborrado' => false
        ));
        return $consulta->setMaxResults($limit)->getResult();
    }
    
    public function updateNotificaciones($codigos){
		if(isset($codigos['11']))
			$anuncio = ($codigos['11'])?1:0;
		else
			$anuncio = null;
		
		if(isset($codigos['12']))
			$taremoper = ($codigos['12'])?1:0;
		else
			$taremoper = null;
		
		if(isset($codigos['13']))
			$noticias = ($codigos['13'])?1:0;
		else
			$noticias = null;
		
        $em = $this->getEntityManager();
        $conn = $em->getConnection();
		if($anuncio){
        	$sql = "UPDATE telefono SET telefono.enviar_notificacion=0, telefono.notificacion_anuncio=$anuncio WHERE telefono.inactivo=0 AND telefono.registroborrado=0";
        	$conn->executeUpdate($sql);
		}
		if($taremoper){
			$sql = "UPDATE telefono SET telefono.enviar_notificacion=0, telefono.notificacion_taremoper=$taremoper WHERE telefono.inactivo=0 AND telefono.registroborrado=0";
        	$conn->executeUpdate($sql);
		}
		if($noticias){
			$sql = "UPDATE telefono SET telefono.enviar_notificacion=0, telefono.notificacion_noticias=$noticias WHERE telefono.inactivo=0 AND telefono.registroborrado=0";
        	$conn->executeUpdate($sql);
		}
    }
    
    public function enviarNotificaciones(){
        $em = $this->getEntityManager();
        $conn = $em->getConnection();
        $sql = "UPDATE telefono SET telefono.enviar_notificacion=1 WHERE telefono.inactivo=0 AND telefono.registroborrado=0";
        $conn->executeUpdate($sql);
    }
}